# MongoDB Atlas Cloud Connection (Using Environment Variable - SECURE)
spring.data.mongodb.uri=${MONGODB_URI}

# Tell Spring Boot which database to use
spring.data.mongodb.database=event_management_db

# Port configuration
server.port=8081

# Logging level
logging.level.org.springframework.data.mongodb=DEBUG