# MongoDB Atlas Cloud Connection
spring.data.mongodb.uri=mongodb+srv://vikumprabhath4_db_user:Yv5NDAXeA6AnGQ65@cluster0.b7a1gzg.mongodb.net/?appName=Cluster0

# Tell Spring Boot EXACTLY which database name to use inside the cluster
spring.data.mongodb.database=event_management_db

# Port configuration (standard)
server.port=8080

# Logging level
logging.level.org.springframework.data.mongodb=DEBUG