# MongoDB Atlas Cloud Connection (Using Environment Variable - SECURE)
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://vikumprabhath4_db_user:MyNewSecurePass123!@cluster0.b7a1gzg.mongodb.net/?appName=Cluster0}

# Tell Spring Boot which database to use
spring.data.mongodb.database=event_management_db

# Port configuration
server.port=8081

# Logging level
logging.level.org.springframework.data.mongodb=DEBUG

# Email Configuration (For Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sellout.support@gmail.com
spring.mail.password=yswz qbpg znss jxqz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true